import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Digital Fault Recorder",
  //description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-gradient-to-br from-slate-950 via-slate-900 to-slate-950 text-gray-100 min-h-screen flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
